lastUpdated = "2019-02-11 20:37:11"
serviceName = "my-file"
version = "5.0.3"

[[apps]]
  appName = "predix-acs"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "testPackageName11"
    type = "testPackageType11"

  [[apps.packages]]
    name = "testPackageName12"
    type = "testPackageType12"

  [[apps.packages]]
    name = "testPackageName3"
    type = "testPackageType3"
    version = "testPackageVersion3"

  [[apps.packages]]
    name = "testPackageName4"
    type = "testPackageType4"
    version = "testPackageVersion4"
