lastUpdated = "2019-02-12 21:07:35"
serviceName = "my-file"
version = "5.0.3"

[[apps]]
  appName = "predix-acs"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "testPackageName11"
    type = "testPackageType11"

  [[apps.packages]]
    name = "testPackageName4"
    type = "testPackageType4"
    version = "testPackageVersion4"

  [[apps.packages]]
    name = "testPackageName5"
    type = "testPackageType5"
    version = "testPackageVersion5"

  [[apps.packages]]
    name = "testPackageName6"
    type = "testPackageType6"
    version = "testPackageVersion6"

  [[apps.packages]]
    name = "testPackageName8"
    type = "testPackageType8"
    version = "testPackageVersion8"
