lastUpdated = "2019-02-12 21:48:48"
serviceName = "my-file1"
version = "5.0.3"

[[apps]]
  appName = "predix-acs"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "testPackageName125"
    type = "testPackageType125"
    version = "testPackageVersion125"
