lastUpdated = "2019-02-12 20:48:31"
serviceName = "my-file"
version = "5.0.3"

[[apps]]
  appName = "predix-acs"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "testPackageName11"
    type = "testPackageType11"

  [[apps.packages]]
    name = "testPackageName4"
    type = "testPackageType4"
    version = "testPackageVersion4"
