lastUpdated = "2019-02-13 00:02:29"
serviceName = "my-file3"
version = "5.0.5"

[[apps]]
  appName = "predix-acs"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.5"

  [[apps.packages]]
    name = "testPackageName126"
    type = "testPackageType126"
    version = "testPackageVersion126"

  [[apps.packages]]
    name = "testPackageName127"
    type = "testPackageType127"
    version = "testPackageVersion127"
