lastUpdated = "2019-02-13 10:54:52"
serviceName = "my-file3"
version = "5.0.8"

[[apps]]
  appName = "predix-acs"
  pipeline = "access-control-service/5.0.5/Jenkinsfile_DeployPPC-5.0.6"

  [[apps.packages]]
    name = "testPackageName126"
    type = "testPackageType126"
    version = "testPackageVersion126"

  [[apps.packages]]
    name = "testPackageName127"
    type = "testPackageType127"
    version = "testPackageVersion127"

  [[apps.packages]]
    name = "testPackageName128"
    type = "testPackageType128"
    version = "testPackageVersion128"

  [[apps.packages]]
    name = "testPackageName129"
    type = "testPackageType129"
    version = "testPackageVersion129"
